NekretnineWeb/NekretnineWeb/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NekretnineWeb.Data;
using NekretnineWeb.Models;
using NekretnineWeb.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NekretnineWeb.Controllers
{
    public class PropertyController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IPropertyRepository _propertyRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICityRepository _cityRepository;
        private readonly ApplicationDbContext _applicationDbContext;

        public PropertyController(ApplicationDbContext applicationDbContext, IPropertyRepository propertyRepository, ICategoryRepository categoryRepository, ICityRepository cityRepository, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _propertyRepository = propertyRepository;
            _categoryRepository = categoryRepository;
            _cityRepository = cityRepository;
            _signInManager = signInManager;
            _userManager = userManager;
            _applicationDbContext = applicationDbContext;
        }
        //GET:Property/5
        [HttpGet("{id}")]
        public IActionResult EditProperty([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var propertyViewModel = new PropertyViewModel
            {
                property = _propertyRepository.Properties.SingleOrDefault(p => p.PropertyId == id),
            };

            propertyViewModel.category = propertyViewModel.property.CategoryId;
            propertyViewModel.city = propertyViewModel.property.CityId;

            if (propertyViewModel.property == null)
            {
                return NotFound();
            }
            //return View("../Property/EditProperty", propertyViewModel);
            return View("../Property/EditProperty", propertyViewModel);
        }
        [Authorize]
        //GET:Property/
        public async Task<IActionResult> MyProperty()
        {
            var user = await _userManager.GetUserAsync(User);
            IEnumerable<Property> properties = _propertyRepository.Properties.Where(p => p.Customer == user)
                   .OrderBy(p => p.PropertyId);
            var myProperty = new PropertiesListViewModel
            {
                Properties = properties
            };
            return View(myProperty);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllProperty()
        {
            var user = await _userManager.GetUserAsync(User);
            IEnumerable<Property> properties = _propertyRepository.Properties;
            var allProperty = new PropertiesListViewModel
            {
                Properties = properties
            };
            return View("MyProperty", allProperty);
        }
        public IActionResult DeleteProperty(int id)
        {
            var property = _propertyRepository.Properties.Where(p => p.PropertyId == id);

            if (property != null)
            {
                _propertyRepository.DeleteProperty((Property)property);
            }

            return View("MyProperty");
        }
        public ViewResult List(string category)
        {
            IEnumerable<Property> properties;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                properties = _propertyRepository.Properties.OrderBy(p => p.PropertyId);
                currentCategory = "All";
            }
            else
            {
                properties = _propertyRepository.Properties.Where(p => p.Category.CategoryName == category)
                   .OrderBy(p => p.PropertyId);
                currentCategory = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }

            return View(new PropertiesListViewModel
            {
                Properties = properties,
                CurrentCategory = currentCategory,
            });
        }
        [Authorize]
        public async Task<IActionResult> AddProperty(PropertyViewModel model)
        {
            var categ = _categoryRepository.Categories.OrderBy(c => c.CategoryName).Select(x => new { IdCa = x.CategoryId, ValueCa = x.CategoryName });
            var cit = _cityRepository.Cities.OrderBy(c => c.CityName).Select(x => new { IdCi = x.CityId, ValueCi = x.CityName });

            //var model1 = new PropertyViewModel();
            //model1.categories = new SelectList(categ, "IdCa", "ValueCa");
            //model1.cities = new SelectList(cit, "IdCi", "ValueCi");
            var user = await _userManager.GetUserAsync(User);

            //int i = 0;
            //if (i > 0)
            //{
            //    property.Address = model.property.Address;
            //    property.Area = model.property.Area;
            //    property.Baths = model.property.Baths;
            //    property.Category = model.property.Category;
            //    property.City = model.property.City;
            //    property.Date = DateTime.Now;
            //    property.Email = model.property.Email;
            //    property.ImageUrl = model.property.ImageUrl;
            //    property.LongDescription = model.property.LongDescription;
            //    property.PhoneNumber = model.property.PhoneNumber;
            //    property.Price = model.property.Price;
            //    property.Rooms = model.property.Rooms;
            //    property.ShortDescription = model.property.ShortDescription;  model.property != null
            //}
            if (!ModelState.IsValid)
            {
                int a, b;
                a = model.property.CategoryId;
                b = model.property.CityId;

                Property property = new Property
                {
                    Customer = user,
                    Address = model.property.Address,
                    Area = model.property.Area,
                    Baths = model.property.Baths,
                    CategoryId = model.property.CategoryId,
                    Category = _categoryRepository.Categories.ElementAt(a-1),
                    CityId = model.property.CityId,
                    City = _cityRepository.Cities.ElementAt(b-1),
                    Date = DateTime.Now,
                    Email = model.property.Email,
                    ImageUrl = model.property.ImageUrl,
                    LongDescription = model.property.LongDescription,
                    PhoneNumber = model.property.PhoneNumber,
                    Price = model.property.Price,
                    Rooms = model.property.Rooms,
                    Tel = user.PhoneNumber,
                    Mail = user.Email,
                    ShortDescription = model.property.ShortDescription
                };
                //Property prop = new Property();
                //prop.Customer = user;
                //prop.Address = model.property.Address;
                //prop.Area = model.property.Area;
                //prop.Baths = model.property.Baths;

                //prop.Date = DateTime.Now;
                //prop.Email = model.property.Email;
                //prop.ImageUrl = model.property.ImageUrl;
                //prop.LongDescription = model.property.LongDescription;
                //prop.PhoneNumber = model.property.PhoneNumber;
                //prop.Price = model.property.Price;
                //prop.Rooms = model.property.Rooms;
                //prop.ShortDescription = model.property.ShortDescription;
                //prop.CategoryId = model.property.CategoryId;
                //prop.CityId = model.property.CityId;
                //prop.City = _cityRepository.Cities.ElementAt(b-1);
                //prop.Category = _categoryRepository.Categories.ElementAt(a-1);

                _propertyRepository.CreateProperty(property);
                return RedirectToAction("Index", "Home");

            }
            model.categories = new SelectList(categ, "IdCa", "ValueCa");
            model.cities = new SelectList(cit, "IdCi", "ValueCi");
            return View(model);
        }
        public IActionResult EdiProperty(int id)
        {
            var propertyViewModel = new PropertyViewModel
            {
                property = (Property)_propertyRepository.Properties.Where(p => p.PropertyId == id)
            };
            //if (propertyViewModel == null)
            //{
            //    return NotFound();
            //}
            //return View("AddProperty", propertyViewModel);
            return View("../Home/Index");
        }
        public IActionResult Details(int id)
        {
            var property = _propertyRepository.GetPropertyById(id);
            var city = _cityRepository.Cities.FirstOrDefault(c => c.CityId == property.CityId);
            var category = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryId == property.CategoryId);
            //var user = _applicationDbContext.Users.FirstOrDefault(u => u.Id == property.Customer.Id);
            var details = new DetailsViewModel
            {
                Property = property,
                Category = category,
                City = city,
                //User = user
            };
            if (details == null)
                return NotFound();

            return View(details);
        }
    }
}

NekretnineWeb/NekretnineWeb/Views/Shared/Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                <li data-target="#carousel-example-generic" data-slide-to="5"></li>
                <li data-target="#carousel-example-generic" data-slide-to="6"></li>
                <li data-target="#carousel-example-generic" data-slide-to="7"></li>
                <li data-target="#carousel-example-generic" data-slide-to="8"></li>
                <li data-target="#carousel-example-generic" data-slide-to="9"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel11.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel12.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel4.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel5.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel6.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel7.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel8.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel9.jpg" alt="" style="height:600px; width:1200px">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel10.jpg" alt="" style="height:600px; width:1200px">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

NekretnineWeb/NekretnineWeb/Views/Shared/PropertyOverviewSummary.cshtml
@model DetailsViewModel
@inject ApplicationDbContext context


<div class="col-sm-4 col-lg-4 col-md-4">
    <a asp-controller="Property" asp-action="Details" asp-route-id="@Model.Property.PropertyId">
        <div class="thumbnail">
            <div class="photo">
                @if(Model.Property.ImageUrl == null){
                    <img src="~/images/no-image.jpg" alt="" style="height:200px">
                }
                @if(Model.Property.ImageUrl != null){
                <img src="@Model.Property.ImageUrl" alt="" style="height:200px">
                }
            </div>
            <div class="caption">
                <h4 class="pull-left">@context.Cities.FirstOrDefault(c => c.CityId == Model.Property.CityId).CityName</h4>
                <h4 class="pull-right">@context.Categories.FirstOrDefault(c => c.CategoryId == Model.Property.CategoryId).CategoryName</h4><br /><br />
                <h3 class="pull-left">@Model.Property.Area.ToString("") m2</h3>
                <h3 class="pull-right">@Model.Property.Price.ToString("") €</h3><br />
            </div>
        </div>
    </a>
</div>

NekretnineWeb/NekretnineWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NekretnineWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NekretnineWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Početna</a></li>
                    @if (UserManager.GetUserName(User) != "Admin")
                    {
                        <li><a asp-area="" asp-controller="Property" asp-action="AddProperty">Dodaj oglas</a></li>
                    }
                    @if (UserManager.GetUserName(User) == "Admin")
                    {
                        <li><a asp-area="" asp-controller="api/Customer" asp-action="Index">Korisnici</a></li>
                        <li><a asp-area="" asp-controller="Property" asp-action="AllProperty">Oglasi</a></li>
                    }
                    @if (SignInManager.IsSignedIn(User) && UserManager.GetUserName(User) != "Admin")
                    {
                        <li><a asp-area="" asp-controller="Property" asp-action="MyProperty">Moji oglasi</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

        @*<footer>
                <hr />
                <p>&copy; 2018 - NekretnineWeb</p>
            </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>